---
driver:
  name: vagrant
  customize:
    memory: 2048
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: vagrant-lamp
    run_list: recipe[bk_init]
